ProjectManagementSystem/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('users', 'UserController');
Route::resource('roles', 'RoleController');
Route::resource('permissions', 'PermissionController');
Route::resource('tasks', 'TaskController');
Route::resource('technologies', 'TechnologyController');
Route::resource('projects', 'ProjectsController');

Route::middleware(["rolespermissionsverifier:roles:Admin;User|permissions:adminperm"])->group(function (){
    Route::resource('users', 'UserController');
    Route::resource('roles', 'RoleController');
    Route::resource('permissions', 'PermissionController');
    Route::resource('technologies', 'TechnologyController');
    Route::resource('projects', 'ProjectsController');
});

Route::middleware(["rolespermissionsverifier:roles:Admin;User|permissions:EditProfile"])->group(function (){
    Route::resource('users', 'UserController', ['only' => [
        'edit', 'update'
    ]]);
});

Route::middleware(["rolespermissionsverifier:roles:Admin;User|permissions:ClientSee"])->group(function (){
    Route::resource('users', 'UserController', ['only' => [
        'index'
    ]]);
});

Route::middleware(["rolespermissionsverifier:roles:Admin;User|permissions:attachTechnologies"])->group(function (){
    Route::resource('technologies', 'TechnologyController', ['only' => [
        'index', 'create', 'edit', 'update'
    ]]);
});

Route::middleware(["rolespermissionsverifier:roles:ProjectMan;"])->group(function (){
    Route::resource('users', 'UserController', ['only' => [
        'showEmployees', 'showClients'
    ]]);
});

Route::get('setlocale/{locale}', function ($locale) {
    if (in_array($locale, \Config::get('app.locales'))) {
# Проверяем, что у пользователя выбран доступный язык
        Session::put('locale', $locale);
# И устанавливаем его в сессии под именем locale
    }
    return redirect()->back();
# Редиректим его <s>взад</s> на ту же страницу
});

Route::put('inactive/{id}',array('uses' => 'UserController@inactive', 'as' => 'users.inactive'), function ($id){

});

Route::get('showEmployees/',array('uses' => 'UserController@showEmployees', 'as' => 'users.showEmployees'));

Route::get('showClients/',array('uses' => 'UserController@showClients', 'as' => 'users.showClients'));

ProjectManagementSystem/app/models/Task.php
<?php

namespace App\models;

use Illuminate\Database\Eloquent\Model;

class Task extends Model
{
    /**
     * Table, connected with model.
     *
     * @var string
     */
    protected $table = 'tasks';
    /**
     * Defines if timestamps updated_at and created_at have to be processed.
     *
     * @var bool
     */
    public $timestamps = false;

    protected $fillable = [
        'name',
        'description',
        'project_id',
        'start',
        'end',
        'status'
    ];

}

ProjectManagementSystem/app/Http/Controllers/TaskController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\models\Task;
use App\models\Projects;
class TaskController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $tasks = Task::all(); //get all tasks
        $projects=Projects::all();
        return view('tasks.index', ['tasks' => $tasks,'projects'=>$projects]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $projects = Projects::all();
        $statuses = ['new' => 'new',
            'in_progress' => 'in_progress',
            'completed' => 'completed',
            'canceled' => 'canceled'];
        return view('tasks.create', ['projects_name'=>$projects, 'statuses' => $statuses]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //Validate name and project_id field
        $this->validate($request, [
                'name'=>'required|max:150',
                'project_id' =>'required',
            ]
        );
        $task = new Task();
        $task->name = $request['name'];
        $task->project_id = $request['project_id'];
        $task->description =  $request['description'];
        $task->start =  $request['start'];
        $task->end = $request['end'];
        $task->status = $request['status'];

        $task->save();

        flash('Task '. $task->name.' was added!');
        return redirect()->route('tasks.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return redirect('tasks');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $task = Task::findOrFail($id);
        $projects = Projects::all();
        $statuses = ['new' => 'new',
            'in_progress' => 'in_progress',
            'completed' => 'completed',
            'canceled' => 'canceled'];
        return view('tasks.edit', compact('task', 'projects', 'statuses'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $task = Task::findOrFail($id);
        $this->validate($request, [
                'name'=>'required|max:150',
                'project_id' =>'required',
            ]
        );

       // $task->fill($request)->save();

        $task->name = $request['name'];
        $task->project_id = $request['project_id'];
        $task->description =  $request['description'];
        $task->start =  $request['start'];
        $task->end = $request['end'];
        $task->status = $request['status'];

        $task->save();

        flash('Task '. $task->name.' was updated!');
        return redirect()->route('tasks.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $task = Task::findOrFail($id);
        $task->delete();

        flash('Task ' . $task->name . ' was deleted!');
        return redirect()->route('tasks.index');
    }
}

ProjectManagementSystem/resources/views/tasks/create.blade.php
@extends('layouts.app')

@section('title', '| Add Task')

@section('content')

    <div class='col-lg-4 col-lg-offset-4'>

        <h1><i class='fa fa-key'></i> {{__('Add Task')}}</h1>
        <hr>

        {{ Form::open(array('url' => 'tasks')) }}

        <div class="form-group">
            {{ Form::label('name', 'Name') }}
            {{ Form::text('name', null, array('class' => 'form-control')) }}
        </div><div class="form-group">
            {{ Form::label('description', 'Description') }}
            {{ Form::textarea('description', null, array('class' => 'form-control')) }}
        </div>
        <div class="form-group">
            {{ Form::label('start', 'Starts') }}
            {{ Form::date('start', \Carbon\Carbon::now()) }}
        </div>
        <div class="form-group">
            {{ Form::label('end', 'Ends') }}
            {{ Form::date('end', \Carbon\Carbon::now()) }}
        </div>

        <div class="form-group">
            {{ Form::label('project_id', 'Project') }}
            {{ Form::select('project_id',  $projects_name->pluck('name'))}}
        </div>

        <div class="form-group">
            {{ Form::label('status', 'Status') }}
            {{ Form::select('status', $statuses)}}
        </div>

        {{ Form::submit('Add', array('class' => 'btn btn-primary')) }}

        {{ Form::close() }}

    </div>

@endsection

ProjectManagementSystem/resources/views/tasks/edit.blade.php
@extends('layouts.app')

@section('title', '| Edit Role')

@section('content')

    <div class='col-lg-4 col-lg-offset-4'>
        <h1><i class='fa fa-key'></i> Edit Task: {{$task->name}}</h1>
        <hr>

        {{ Form::model($task, array('route' => array('tasks.update', $task->id), 'method' => 'PUT')) }}

        <div class="form-group">
            {{ Form::label('name', 'Task Name') }}
            {{ Form::text('name', null, array('class' => 'form-control')) }}
        </div>
        <div class="form-group">
            {{ Form::label('description', 'Description') }}
            {{ Form::text('description', null, array('class' => 'form-control')) }}
        </div>

        <div class="form-group">
            {{ Form::label('start', 'Starts') }}
            {{ Form::date('start') }}
        </div>
        <div class="form-group">
            {{ Form::label('end', 'Ends') }}
            {{ Form::date('end')  }}
        </div>

        <div class="form-group">
            {{ Form::label('project_id', 'Project') }}
            {{ Form::select('project_id', $projects->pluck('name'))}}
        </div>

        <div class="form-group">
            {{ Form::label('status', 'Status') }}
            {{ Form::select('status', $statuses)}}
        </div>

        <br>
        {{ Form::submit('Edit', array('class' => 'btn btn-primary')) }}

        {{ Form::close() }}
    </div>

@endsection

ProjectManagementSystem/resources/views/tasks/index.blade.php
@extends('layouts.app')

@section('title', '| Tasks')

@section('content')

    <div class="col-lg-10 col-lg-offset-1">
        <h1><i class="fa fa-key"></i> {{__('Tasks')}}
           <a href="{{ route('projects.index') }}" class="btn btn-default pull-right">Projects</a>
        </h1>
        <hr>
        <div class="table-responsive">
            <table class="table table-bordered table-striped">
                <thead>
                <tr>
                    <th>{{__('Task')}}</th>
                    <th>{{__('Description')}}</th>
                    <th>{{__('Project')}}</th>
                    <th>{{__('Starts')}}</th>
                    <th>{{__('Ends')}}</th>
                    <th>{{__('Status')}}</th>
                    <th>{{__('Operation')}}</th>
                </tr>
                </thead>
                <tbody>
                @foreach ($tasks as $task)
                    {{--TODO: uncomment when Project model will be created--}}
{{--                    @if(App\models\Project::where('id', $task->project_id)->first()->clients_id == Auth::user()->id)--}}
                    <tr>
                        <td>{{ $task->name }}</td>
                        <td>{{ $task->description }}</td>
                        <td>{{ $task->project_id }}</td>{{-- TODO: change project_id on project name (when project model will be created) --}}
                        <td>{{ $task->start }}</td>
                        <td>{{ $task->end }}</td>
                        <td>{{ $task->status }}</td>
                        <td>
                            <a href="{{ URL::to('tasks/'.$task->id.'/edit') }}" class="btn btn-info pull-left" style="margin-right: 3px;">Edit</a>

                            {!! Form::open(['method' => 'DELETE', 'route' => ['tasks.destroy', $task->id] ]) !!}
                            {!! Form::button('<i class="glyphicon glyphicon-trash"></i> Delete', array('type' => 'submit', 'class' => 'btn btn-danger')) !!}
                            {!! Form::close() !!}
                        </td>
                    </tr>
                {{--@endif--}}
                @endforeach
                </tbody>
            </table>
        </div>

        <a href="{{ URL::to('tasks/create') }}" class="btn btn-success">{{__('Add Task')}}</a>

    </div>
@endsection